# These are supported funding model platforms

github: GuduleLapointe
buy_me_a_coffee: speculoos.world
open_collective: speculoosworld
custom: https://magiiic.com/donate/project/?project=tree-sitter-lsl-ossl
