id = "lsl-ossl"
name = "LSL/OSSL Language"
version = "0.1.0"
schema_version = 1
authors = ["Gudule Lapoite <gudule@speculoos.world>"]
description = "LSL/OSSL Language for Zed IDE"
repository = "https://github.com/GuduleLapointe/lsl-ossl-zed"

[grammars.lsl]
repository = "https://github.com/GuduleLapointe/tree-sitter-lsl-ossl"
commit = "d7429b491f6e0767c96979addde87dc41762634e"
