id = "lsl-ossl"
name = "LSL/OSSL Language"
version = "0.1.0"
schema_version = 1
authors = ["Gudule Lapoite <gudule@speculoos.world>"]
description = "LSL/OSSL Language for Zed IDE"
repository = "https://github.com/GuduleLapointe/lsl-ossl-zed"

[grammars.lsl]
repository = "https://github.com/GuduleLapointe/tree-sitter-lsl-ossl"
commit = "57699cda2a29dc6df7f6c4e3ba3f3dba62fe74f2"

[language_servers.lsl-lsp]
name = "LSL Language Server"
languages = ["LSL"]
