id = "lsl-ossl"
name = "LSL/OSSL Language"
version = "0.1.0"
schema_version = 1
authors = ["Gudule Lapoite <gudule@speculoos.world>"]
description = "LSL/OSSL Language for Zed IDE"
repository = "https://github.com/GuduleLapointe/lsl-ossl-zed"

[grammars.lsl]
repository = "https://github.com/GuduleLapointe/tree-sitter-lsl-ossl"
commit = "68871b54a04385b190a6c1be954c8dec7257d265"
